name = "tldraw-worker"
main = "worker/worker.ts"
compatibility_date = "2024-07-01"

[dev]
port = 5172
ip = "0.0.0.0"

# Set up the durable object used for each tldraw room
[durable_objects]
bindings = [
    { name = "TLDRAW_DURABLE_OBJECT", class_name = "TldrawDurableObject" },
]

# We store rooms and asset uploads in an R2 bucket
[[r2_buckets]]
binding = 'TLDRAW_BUCKET'
bucket_name = 'tldraw'
preview_bucket_name = 'tldraw-preview'

# Environment variables
[vars]
# Replace with your actual Clerk secret key
CLERK_SECRET_KEY=sk_test_CCqHKAlY6pNmg1LRfM4Sn8EJH0oe30QZe0jbzsxUx7

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "TldrawDurableObject" ]