name = "tldraw-worker"
main = "worker/worker.ts"
compatibility_date = "2024-07-01"

[dev]
port = 5172
ip = "0.0.0.0"
vars = { ENVIRONMENT = "development" }

# Set up the durable object used for each tldraw room
[durable_objects]
bindings = [
    { name = "TLDRAW_DURABLE_OBJECT", class_name = "TldrawDurableObject" },
]

# We store rooms and asset uploads in an R2 bucket
[[r2_buckets]]
binding = 'TLDRAW_BUCKET'
bucket_name = 'tldraw'
preview_bucket_name = 'tldraw-preview'

# Environment variables
[vars]
# Replace with your actual Clerk keys
CLERK_SECRET_KEY="sk_live_dJnyu4n5NGVpedSBsuLOswJpPzpTdSDkN7gFNQ8sxs"
CLERK_PUBLISHABLE_KEY="pk_live_Y2xlcmsuZG1raXQuaW8k"
ENVIRONMENT="production"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "TldrawDurableObject" ]

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.